---
  - name: "show remote environment"
    shell: env
  - name: "copy artifact to ec2"
    become: yes
    synchronize:
      src: ~/project/artifact.tar.gz
      dest: ~/
      recursive: true
  - name: "extract artifact"
    unarchive:
      src: ~/project/artifact.tar.gz
      dest: ~/
  - name: "start server"
    become: true
    shell: |
      npm install
      pm2 stop default
      sudo pm2 start npm -- start
    args:
      chdir: ~/dist
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}" 